version: '3.8'

services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge